### ISSUE TITLE
Move constructors material

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-objects-modeling#10]
https://github.com/ga-wdi-boston/js-objects-constructors

**Comment by jrhorn424** [comment]
More detail: The constructors material is already duplicated there. It should be removed from this repo.

**Comment by GA-MEB** [comment]
@jrhorn424 : There is no longer any material on constructors in this repo. Can we close this issue?

**Comment by jrhorn424** [comment]
Confirmed. Thanks.
