### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/js-objects-modeling#12]
Suggest "js-abstraction-modeling"

**Comment by jrhorn424** [comment]
Hm. How about `js-objects-modeling`, so it's clear that it goes in a sequence with `js-objects-this` and friends?

**Comment by gaand** [comment]
:thumbsup:

**Comment by berziiii** [comment]
@jrhorn424 thoughts? Are we good for `js-objects`?

**Comment by berziiii** [comment]
Next time. (from @jrhorn424)

**Comment by laurenfazah** [comment]
All set to close @jrhorn424

**Comment by gaand** [comment]
@jrhorn424 Closing because its name makes it part of the sequence.
