### ISSUE TITLE
Markdown formatting issue in TV example.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/js-objects-modeling#13]
List heading got collapsed into the previous list item.

**Comment by laurenfazah** [comment]
Looks like this might have been taken care of? @MattB-GA-Boston

**Comment by laurenfazah** [comment]
Scratch that @MattB-GA-Boston, found it and fixed it.

**Comment by berziiii** [comment]
Since it's been fixed, closing the issue. Feel free to reopen if necessary. Thanks.
