### ISSUE TITLE
Related material

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-objects-modeling#14]
https://github.com/ga-wdi-boston/js-modeling-problem-solving

**Comment by laurenfazah** [comment]
@jrhorn424 were you hoping to just link to this in the readme?

**Comment by gaand** [comment]
I believe it's meant as a reference for the person refreshing the lesson.

**Comment by berziiii** [comment]
It was meant as a reminder to archive the related material after it had been gleaned for additional content. (from @jrhorn424)

**Comment by jrhorn424** [comment]
@berziiii the necessary content has been migrated, yes?

**Comment by raq929** [comment]
I'm suggesting that user stories be migrated to the project planning repo.
https://github.com/ga-wdi-boston/game-project-scope-study/issues/61

I think this issue can be closed.

**Comment by raq929** [comment]
@jrhorn424 is it OK to close?

**Comment by jrhorn424** [comment]
I'm ok with this. Thanks @raq929
