### ISSUE TITLE
Combine with "this" repo

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-objects-modeling#2]
In teaching today, it made more sense to cover the "basics of `this`" as part of the lesson, rather than relegate it to a separate lesson.

https://github.com/ga-wdi-boston/js-objects-this-08

The lab in the follow-up lesson builds on the current lab, and the assessment depends on both lessons.

This will require minor changes to the demo example.

**Comment by GA-MEB** [comment]
@jrhorn424, on reflection, do you still think that `js-objects` should be combined with the lesson on `this`?

**Comment by jrhorn424** [comment]
I do not, in fact, still that is advisable. Thanks for checking!

**Comment by jrhorn424** [comment]
In fact, constructors will be moved into its own lesson, following our strive to make presentations smaller and more targeted.
