### ISSUE TITLE
For the lab, who's 'strength' value should we use?

### ISSUE THREAD

**Issue by resource11** [ga-wdi-boston/js-objects-modeling#4]
In the lab, this paragraph seemed a bit ambiguous:

"Each of these units also has a method called 'attack' which takes another character as an argument. The 'attack' method should print the text "HIT" and force the defender to deduct some amount ('strength') from their 'health'."

Does that mean we are deducting the value of the _attacker's_ strength from the defender's health, or are we using the value of the _defender's_ strength to evaluate the defender's health?

**Comment by GA-MEB** [comment]
This lab has been replaced with a different one. Closing the issue.
